auto: true

#markdown: rdiscount
rouge: true
paginate: 8
permalink: /:title

title: bohaohan.github.io
url: http://bohaohan.github.io/
feed: /atom.xml
author_info: <a href="http://bohaohan.github.io/">Bohaohan</a>
