auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: bohaohan.github.io
url: http://bohaohan.github.io/
feed: /atom.xml
author_info: <a href="http://bohaohan.github.io/">Bohaohan</a>
