auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title

title: Haohan Bo (伯浩瀚)'s Homepage
url: http://bohaohan.github.io/
feed: /atom.xml
author_info: <a href="http://bohaohan.github.io/">Haohan Bo (伯浩瀚)</a>
