auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title

title: bohaohan
url: http://bohaohan.github.io/
feed: /atom.xml
author_info: <a href="http://bohaohan.github.io/">Bohaohan</a>
